# Group of mobs that spawn around the map.
mobs-group:
  chance: 20
  min-amount: 3
  max-amount: 10
  size: 7

# To disable all mobs from spawning, remove all mobs and add "- NONE"
# To retrieve all the mobs, delete this config.yml and restart the server.
allowed-mobs:
  - ALLAY
  - ARMADILLO
  - AXOLOTL
  - BAT
  - BEE
  - CAMEL
  - CAT
  - CHICKEN
  - COD
  - COW
  - DOLPHIN
  - FROG
  - FOX
  - GOAT
  - GLOW_SQUID
  - MOOSHROOM
  - MULE
  - OCELOT
  - PARROT
  - PIG
  - PUFFERFISH
  - RABBIT
  - SALMON
  - SHEEP
  - SNOW_GOLEM
  - SQUID
  - WOLF
  - STRIDER
  - TURTLE
  - VILLAGER
  - WANDERING_TRADER
  - TRADER_LLAMA
  - DROWNED
  - ENDERMAN
  - HOGLIN
  - HUSK
  - MAGMA_CUBE
  - PHANTOM
  - PILLAGER
  - RAVAGER
  - SHULKER
  - SILVERFISH
  - SKELETON
  - SPIDER
  - SPIDER_JOCKEY
  - STRAY
  - VEX
  - VINDICATOR
  - WITCH
  - BLAZE
  - CREEPER
  - ENDER_DRAGON
  - ELDER_GUARDIAN
  - EVOKER
  - GHAST
  - GIANT
  - GUARDIAN
  - HOGLIN_BRUTE
  - MAGMA_CUBE
  - PIGLIN
  - ZOMBIFIED_PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - RAVAGER
  - SHULKER
  - SILVERFISH
  - SKELETON
  - SKELETON_HORSEMAN
  - SLIME
  - SPIDER_JOCKEY
  - STRAY
  - VEX
  - VINDICATOR
  - WITCH
  - WITHER
  - WITHER_SKELETON
  - ZOMBIE
  - ZOMBIE_VILLAGER
  - ENDER_DRAGON
  - WITHER
  - ELDER_GUARDIAN
  - WARDEN